#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

num_monitors="$(xrandr --query | grep ' connected' | wc -l)"  

if (($num_monitors > 1)); then
    bspc monitor HDMI-1 -d I II III
    bspc monitor eDP-1 -d IV V VI
    bspc monitor DP-1 -d VII VIII IX X
else
    bspc monitor Virtual1 -d I II III IV V VI
    bspc monitor eDP-1 -d I II III IV V VI
fi

bspc config border_width         0
bspc config window_gap           20

bspc config left_padding         2
bspc config right_padding        2
bspc config top_padding 40

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config paddingless_monocle  true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-center ~/Downloads/bondrewd.png
sh ./.config/polybar/launch.sh
xsetroot -cursor_name left_ptr &

xrandr --output HDMI-1 --auto --left-of eDP-1
xrandr --output DP-1 --auto --right-of eDP-1
